// Scoped to Freemind so native file dialogs retain their desktop styling.
static const char *freemind_css =
"@define-color fm_bg #101513; @define-color fm_panel #181f1b; @define-color fm_canvas #141a16; @define-color fm_text #dce5df; @define-color fm_accent #a6d6b5; @define-color fm_muted #96a99c; @define-color fm_border #344137; @define-color fm_selection #25362b; @define-color fm_on_accent #14281b; @define-color fm_warning #d7bf8b; @define-color fm_danger #edaaa3; @define-color fm_terminal_canvas #141a16;"
"window.freemind { background: @fm_bg; color: @fm_text; font-family: 'Inter', 'Adwaita Sans', sans-serif; font-size: 13px; }"
".freemind .sidebar { background: @fm_panel; border-right: 1px solid @fm_border; }"
".freemind .brand { min-height: 64px; padding: 0 20px; border-bottom: 1px solid @fm_border; }"
".freemind .brand-name { font-size: 18px; font-weight: 700; letter-spacing: -0.5px; color: @fm_text; }"
".freemind .sidebar-body { padding: 22px 12px 12px; }"
".freemind .section-label { color: @fm_muted; font-size: 10px; font-weight: 700; letter-spacing: 1.4px; padding: 0 10px; }"
".freemind .workspace-item { background: @fm_selection; border: 1px solid @fm_border; border-radius: 8px; padding: 12px 10px; color: @fm_accent; }"
".freemind .workspace-name { font-weight: 600; }"
".freemind .session-list { margin-top: 2px; }"
".freemind button { background: @fm_selection; background-image: none; border: 1px solid @fm_border; border-radius: 7px; color: @fm_text; box-shadow: none; text-shadow: none; min-height: 30px; padding: 3px 12px; font-weight: 500; }"
".freemind button:hover { background: @fm_selection; border-color: @fm_border; color: @fm_text; }"
".freemind button:active { background: @fm_selection; }"
".freemind button:focus-visible { outline: 2px solid @fm_accent; outline-offset: 2px; }"
".freemind button.primary { background: @fm_accent; border-color: @fm_accent; color: @fm_on_accent; font-weight: 650; }"
".freemind button.primary:hover { background: @fm_accent; border-color: @fm_accent; }"
".freemind button.flat { background: transparent; border-color: transparent; color: @fm_muted; }"
".freemind button.flat:hover { background: @fm_selection; color: @fm_text; }"
".freemind button.icon-button { min-height: 26px; min-width: 26px; padding: 1px; border-radius: 5px; }"
".freemind menubutton.icon-button > button { min-height: 26px; min-width: 26px; padding: 1px; border-radius: 5px; background: transparent; border-color: transparent; color: @fm_muted; }"
".freemind menubutton.icon-button > button:hover { background: @fm_selection; color: @fm_text; }"
".freemind button.close:hover { background: @fm_selection; color: @fm_danger; }"
".freemind button.session { background: transparent; border-color: transparent; padding: 10px; font-weight: 400; }"
".freemind button.session:hover { background: @fm_selection; }"
".freemind button.session.selected { background: @fm_selection; color: @fm_text; }"
".freemind .session-number { font-family: monospace; font-size: 10px; color: @fm_muted; }"
".freemind .sidebar-footer { border-top: 1px solid @fm_border; padding: 16px 20px; color: @fm_muted; font-size: 11px; }"
".freemind .topbar { min-height: 64px; padding: 0 12px; border-bottom: 1px solid @fm_border; background: @fm_panel; }"
".freemind .page-title { font-size: 14px; font-weight: 600; color: @fm_text; }"
".freemind .muted { color: @fm_muted; }"
".freemind .path { color: @fm_muted; font-size: 11px; }"
".freemind .count { background: @fm_selection; color: @fm_muted; border-radius: 5px; padding: 2px 7px; font-size: 10px; }"
".freemind .workspace-content { padding: 18px; }"
".freemind .pane { background: @fm_canvas; border: 1px solid @fm_border; border-radius: 10px; }"
".freemind .pane.focused { border-color: @fm_accent; box-shadow: 0 0 0 1px alpha(@fm_accent, 0.08); }"
".freemind .pane-header { min-height: 40px; padding: 0 10px 0 14px; background: @fm_panel; border-bottom: 1px solid @fm_border; border-radius: 9px 9px 0 0; }"
".freemind .pane.focused .pane-header { background: @fm_selection; }"
".freemind .pane-title { font-size: 12px; font-weight: 600; }"
".freemind .pane-icon { color: @fm_accent; }"
".freemind .status { font-size: 10px; color: @fm_muted; padding: 3px 7px; }"
".freemind .status.busy { color: @fm_warning; }"
".freemind .status.approval { color: @fm_warning; background: @fm_selection; border-radius: 4px; }"
".freemind .status.done { color: @fm_accent; }"
".freemind .terminal-wrap { padding: 12px; background: @fm_terminal_canvas; }"
".freemind vte-terminal { padding: 0; }"
".freemind .pane-footer { padding: 5px 14px 8px; color: @fm_muted; font-size: 10px; }"
".freemind .empty-title { font-size: 25px; font-weight: 650; letter-spacing: -0.6px; color: @fm_text; }"
".freemind .empty-description { color: @fm_muted; font-size: 13px; }"
".freemind .empty-mark { color: @fm_accent; margin-bottom: 12px; }"
".freemind .empty-hint { color: @fm_muted; font-size: 11px; margin-top: 12px; }"
".freemind .error-banner { margin: 0 18px; padding: 10px 14px; border: 1px solid @fm_danger; background: @fm_selection; color: @fm_warning; border-radius: 7px; }"
".freemind .statusbar { min-height: 28px; padding: 0 20px; border-top: 1px solid @fm_border; color: @fm_muted; font-size: 10px; }"
".freemind .online { color: @fm_accent; }"
".freemind popover contents { background: @fm_panel; border: 1px solid @fm_border; border-radius: 9px; padding: 6px; }"
".freemind popover button { border-color: transparent; background: transparent; }"
".freemind .settings-top { padding: 24px 28px 18px; border-bottom: 1px solid @fm_border; background: @fm_panel; }"
".freemind .settings-page { padding: 8px 28px 28px; }"
".freemind .settings-heading { font-size: 16px; font-weight: 650; color: @fm_text; }"
".freemind .setting-row { min-height: 42px; }"
".freemind .setting-label { color: @fm_text; }"
".freemind .settings-feedback { padding: 14px 28px; border-top: 1px solid @fm_border; color: @fm_muted; }"
".freemind .settings-feedback.error { color: @fm_danger; }"
".freemind entry, .freemind textview, .freemind textview text { background: @fm_canvas; color: @fm_text; caret-color: @fm_accent; }"
".freemind entry, .freemind .settings-input { border: 1px solid @fm_border; border-radius: 7px; padding: 8px; }"
".freemind switch { background: @fm_selection; border: 1px solid @fm_border; }"
".freemind switch:checked, .freemind scale highlight { background: @fm_accent; }"
".freemind switch slider { background: @fm_text; border-radius: 50%; }"
".freemind dropdown popover listview { background: @fm_panel; color: @fm_text; }"
".freemind dropdown popover row:selected, .freemind stackswitcher button:checked { background: @fm_selection; color: @fm_accent; }"
".freemind button:disabled { opacity: 0.45; }"
".freemind paned > separator { min-width: 5px; min-height: 5px; background: @fm_border; }"
".freemind paned > separator:hover { background: @fm_accent; }"
".freemind .file-panel { background: @fm_panel; }"
".freemind .git-panel { background: @fm_panel; padding: 14px; }"
".freemind .content-toolbar { padding: 9px 10px; border-bottom: 1px solid @fm_border; }"
".freemind .content-toolbar button { font-size: 11px; min-height: 24px; padding: 2px 6px; }"
".freemind .file-row, .freemind .workspace-row { background: transparent; border-color: transparent; border-radius: 5px; padding: 5px 8px; font-size: 12px; font-weight: 400; }"
".freemind .file-row:hover, .freemind .workspace-row:hover { background: @fm_selection; }"
".freemind .file-row.selected, .freemind .workspace-row.selected { background: @fm_selection; color: @fm_accent; }"
".freemind .tree-search, .freemind .document-search { margin: 8px 10px; font-size: 11px; }"
".freemind .source-editor { font-family: monospace; font-size: 11pt; }"
".freemind .editor-panel { background: @fm_canvas; }"
".freemind .markdown-preview { padding: 28px; font-size: 14px; line-height: 1.6; }"
".freemind .git-feedback { padding: 12px; color: @fm_muted; }"
".freemind .command-list { background: @fm_bg; color: @fm_text; }"
".freemind .command-list row:selected { background: @fm_selection; color: @fm_accent; }"
".freemind .view-tabs button { min-height: 24px; padding: 2px 6px; font-size: 11px; }"
".freemind .topbar > button.primary { min-height: 28px; padding: 2px 8px; font-size: 12px; }"
".freemind .file-row, .freemind .workspace-row { min-height: 22px; padding: 3px 6px; }"
".freemind .tree-search, .freemind .document-search { min-height: 24px; padding: 2px 8px; }"
".freemind button.session { min-height: 22px; padding: 7px 10px; }"
".freemind .view-tabs button { background: transparent; border-color: transparent; color: @fm_muted; }"
".freemind .view-tabs button.selected { background: @fm_selection; color: @fm_accent; }"
".freemind button.path-button { min-height: 14px; padding: 0; border: none; }";
